FROM node:20-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files and TypeScript configs
COPY package.json pnpm-lock.yaml ./
COPY tsconfig.json tsconfig.build.json ./

# Install dependencies
RUN pnpm install

# Copy email templates
COPY src/email/templates ./src/email/templates

# Create uploads directory
RUN mkdir -p uploads && chmod 777 uploads

# Expose the port your app runs on
EXPOSE 3000

# Start the application in dev mode
CMD ["pnpm", "start:dev"] 