name: Deploy Review App
on:
  # Run this workflow on every PR event. Existing review apps will be updated when the PR is updated.
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: iad
  FLY_ORG: personal

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Check PR preview database status
        if: github.event.action != 'closed'
        run: |
          echo "Checking PR preview database status..."
          
          if fly status -a red-cloud-4808 --json | jq -e '.Status == "running"' > /dev/null 2>&1; then
            echo "✅ PR preview database is running"
          else
            echo "⚠️  PR preview database is stopped"
            echo "The PR app may fail to connect to the database"
            echo "You may need to manually start it with: npm run preview-db:start"
          fi

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: pr-${{ github.event.number }}-project-management-api
          postgres: red-cloud-4808
          secrets: |
            JWT_SECRET=review-app-jwt-secret-key-2024
            JWT_REFRESH_SECRET=review-app-jwt-refresh-secret-key-2024
            PROJECT_NAME=project-management
            FRONTEND_URL=https://review-app-frontend.example.com
            GOOGLE_CLIENT_ID=review-app-google-client-id
            GOOGLE_CLIENT_SECRET=review-app-google-client-secret
            GOOGLE_CALLBACK_URL=https://pr-${{ github.event.number }}-project-management-api.fly.dev/auth/google/callback
            SMTP_HOST=smtp.gmail.com
            SMTP_PORT=587
            SMTP_USER=review-app@example.com
            SMTP_PASS=review-app-email-pass
            SMTP_FROM_EMAIL=review-app@example.com
            CLOUDINARY_CLOUD_NAME=review-app-cloud
            CLOUDINARY_API_KEY=review-app-api-key
            CLOUDINARY_API_SECRET=review-app-api-secret

      - name: Wait for app to be ready
        if: github.event.action != 'closed'
        run: |
          echo "Waiting for app to be ready..."
          APP_NAME="pr-${{ github.event.number }}-project-management-api"
          
          # Wait for the app to be running
          for i in {1..30}; do
            if fly status -a $APP_NAME --json | jq -e '.Status == "running"' > /dev/null 2>&1; then
              echo "✅ App is running"
              break
            else
              echo "⏳ Waiting for app to start... (attempt $i/30)"
              sleep 10
            fi
          done
          
          # Wait a bit more for the app to fully initialize
          echo "⏳ Waiting for app to fully initialize..."
          sleep 30

      - name: Health check
        if: github.event.action != 'closed'
        run: |
          APP_NAME="pr-${{ github.event.number }}-project-management-api"
          APP_URL="https://$APP_NAME.fly.dev"
          
          echo "Performing health check on $APP_URL"
          
          # Try to hit the health endpoint
          for i in {1..10}; do
            if curl -f -s "$APP_URL/health" > /dev/null 2>&1; then
              echo "✅ Health check passed"
              break
            else
              echo "⏳ Health check failed, retrying... (attempt $i/10)"
              sleep 15
            fi
          done

      - name: Get deployment URL
        run: echo "DEPLOYMENT_URL=${{ steps.deploy.outputs.url }}" >> $GITHUB_ENV 